# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
excerpt_separator: <!--more-->

# Setup
title:               
tagline:             'A blog about bioinformatics, linux and boring stuff ...'
description:         ''
url:                 http://mrnoutahi.com
baseurl:             'http://mrnoutahi.com/'
paginate:            3
github_username:     maclandrol
twitter_username:    ENoutahi
hostsite:            https://github.com/maclandrol/maclandrol.github.io
hoster:              'github'

# About/contact
author:
  name:              Emmanuel Noutahi
  title:		     PhD student
  school: 			 Université de Montréal
  url:               http://mrnoutahi.com
  email:             emmanuel.noutahi@gmail.com
  google:            https://plus.google.com/+EmmanuelNoutahi/about
# Custom vars
version:             1.0.0
