# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
excerpt_separator: <!--more-->

# Setup
title:               
tagline:             'Sharing my thoughts on bioinformatics, linux, and some boring stuff ...'
description:         ''
url:                 http://blog.mrnoutahi.com
baseurl:             'http://blog.mrnoutahi.com'
paginate:            5
github_username:     maclandrol
twitter_username:    ENoutahi
hostsite:            https://github.com/maclandrol/maclandrol.github.io
hoster:              'github'

# About/contact
author:
  name:              Emmanuel Noutahi
  title:		     PhD student
  school: 			 Université de Montréal
  url:               http://mrnoutahi.com
  email:             emmanuel.noutahi@gmail.com
  google:            https://plus.google.com/+EmmanuelNoutahi/about
# Custom vars
version:             1.0.0
